services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front:/frontend
      - /frontend/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"