services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front:/frontend
      - /frontend/node_modules
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - frontend
